import { Partnership } from '@/types';

// 模拟数据 - 20条合作伙伴记录
export const mockPartnershipData: Partnership[] = [
  {
    id: 1,
    name: '腾讯科技有限公司',
    type: 'enterprise',
    industry: '互联网',
    description: '校企合作项目，提供学生实习和就业机会，共建实验室。',
    startDate: '2022-03-15',
    endDate: '2025-03-14',
    contact: '张经理',
    phone: '13812345678',
    email: 'zhang@tencent.com',
    address: '深圳市南山区高新科技园',
    status: 'active',
  },
  {
    id: 2,
    name: '北京大学',
    type: 'academic',
    industry: '教育',
    description: '学术交流合作，联合培养研究生，共同开展科研项目。',
    startDate: '2021-09-01',
    endDate: '2026-08-31',
    contact: '李教授',
    phone: '010-12345678',
    email: 'li@pku.edu.cn',
    address: '北京市海淀区颐和园路5号',
    status: 'active',
  },
  {
    id: 3,
    name: '华为技术有限公司',
    type: 'enterprise',
    industry: '通信技术',
    description: '产学研合作，共建创新实验室，提供奖学金和实习机会。',
    startDate: '2022-05-20',
    endDate: '2025-05-19',
    contact: '王总监',
    phone: '13987654321',
    email: 'wang@huawei.com',
    address: '深圳市龙岗区坂田华为基地',
    status: 'active',
  },
  {
    id: 4,
    name: '中国科学院',
    type: 'research',
    industry: '科研',
    description: '科研合作，共同申报国家级项目，联合培养博士生。',
    startDate: '2021-10-15',
    endDate: '2026-10-14',
    contact: '赵研究员',
    phone: '010-87654321',
    email: 'zhao@cas.cn',
    address: '北京市海淀区中关村南路',
    status: 'active',
  },
  {
    id: 5,
    name: '阿里巴巴集团',
    type: 'enterprise',
    industry: '电子商务',
    description: '校企合作，共建电商创新中心，提供实习和就业渠道。',
    startDate: '2022-04-10',
    endDate: '2025-04-09',
    contact: '钱经理',
    phone: '13712345678',
    email: 'qian@alibaba.com',
    address: '杭州市余杭区阿里巴巴西溪园区',
    status: 'active',
  },
  {
    id: 6,
    name: '清华大学',
    type: 'academic',
    industry: '教育',
    description: '学术交流与合作，联合举办学术会议，共同培养人才。',
    startDate: '2021-11-05',
    endDate: '2026-11-04',
    contact: '孙教授',
    phone: '010-23456789',
    email: 'sun@tsinghua.edu.cn',
    address: '北京市海淀区清华园',
    status: 'active',
  },
  {
    id: 7,
    name: '百度公司',
    type: 'enterprise',
    industry: '互联网',
    description: '人工智能领域合作，共建AI实验室，提供技术支持和实习机会。',
    startDate: '2022-06-15',
    endDate: '2025-06-14',
    contact: '周总监',
    phone: '13612345678',
    email: 'zhou@baidu.com',
    address: '北京市海淀区西北旺东路10号',
    status: 'active',
  },
  {
    id: 8,
    name: '上海交通大学',
    type: 'academic',
    industry: '教育',
    description: '学术交流与科研合作，共同申报项目，联合培养学生。',
    startDate: '2021-12-10',
    endDate: '2026-12-09',
    contact: '吴教授',
    phone: '021-12345678',
    email: 'wu@sjtu.edu.cn',
    address: '上海市闵行区东川路800号',
    status: 'active',
  },
  {
    id: 9,
    name: '字节跳动',
    type: 'enterprise',
    industry: '互联网',
    description: '新媒体技术合作，共建创新实验室，提供实习和就业机会。',
    startDate: '2022-07-20',
    endDate: '2025-07-19',
    contact: '郑经理',
    phone: '13512345678',
    email: 'zheng@bytedance.com',
    address: '北京市海淀区知春路甲48号',
    status: 'active',
  },
  {
    id: 10,
    name: '中国工程院',
    type: 'research',
    industry: '科研',
    description: '工程技术领域合作，共同开展重大工程项目研究。',
    startDate: '2022-01-15',
    endDate: '2027-01-14',
    contact: '王院士',
    phone: '010-34567890',
    email: 'wang@cae.cn',
    address: '北京市西城区冰窖口胡同2号',
    status: 'active',
  },
  {
    id: 11,
    name: '京东集团',
    type: 'enterprise',
    industry: '电子商务',
    description: '电商物流领域合作，共建实验室，提供实习和就业机会。',
    startDate: '2022-08-10',
    endDate: '2025-08-09',
    contact: '刘经理',
    phone: '13412345678',
    email: 'liu@jd.com',
    address: '北京市亦庄经济开发区科创十一街18号',
    status: 'active',
  },
  {
    id: 12,
    name: '复旦大学',
    type: 'academic',
    industry: '教育',
    description: '学术交流与科研合作，联合培养研究生，共同申报项目。',
    startDate: '2022-02-20',
    endDate: '2027-02-19',
    contact: '陈教授',
    phone: '021-23456789',
    email: 'chen@fudan.edu.cn',
    address: '上海市杨浦区邯郸路220号',
    status: 'active',
  },
  {
    id: 13,
    name: '小米科技',
    type: 'enterprise',
    industry: '电子产品',
    description: '智能硬件领域合作，共建创新实验室，提供实习和就业机会。',
    startDate: '2022-09-15',
    endDate: '2025-09-14',
    contact: '林经理',
    phone: '13312345678',
    email: 'lin@xiaomi.com',
    address: '北京市海淀区清河中街68号',
    status: 'active',
  },
  {
    id: 14,
    name: '中山大学',
    type: 'academic',
    industry: '教育',
    description: '学术交流与科研合作，联合培养学生，共同举办学术会议。',
    startDate: '2022-03-25',
    endDate: '2027-03-24',
    contact: '黄教授',
    phone: '020-12345678',
    email: 'huang@sysu.edu.cn',
    address: '广州市海珠区新港西路135号',
    status: 'active',
  },
  {
    id: 15,
    name: '网易公司',
    type: 'enterprise',
    industry: '互联网',
    description: '游戏开发与互联网技术合作，共建实验室，提供实习和就业机会。',
    startDate: '2022-10-20',
    endDate: '2025-10-19',
    contact: '张总监',
    phone: '13212345678',
    email: 'zhang@netease.com',
    address: '杭州市滨江区网商路599号',
    status: 'active',
  },
  {
    id: 16,
    name: '中国农业大学',
    type: 'academic',
    industry: '教育',
    description: '农业科技领域合作，共同开展科研项目，联合培养研究生。',
    startDate: '2022-04-15',
    endDate: '2027-04-14',
    contact: '李教授',
    phone: '010-45678901',
    email: 'li@cau.edu.cn',
    address: '北京市海淀区清华东路17号',
    status: 'active',
  },
  {
    id: 17,
    name: '科大讯飞',
    type: 'enterprise',
    industry: '人工智能',
    description: '语音识别技术合作，共建AI实验室，提供技术支持和实习机会。',
    startDate: '2022-11-10',
    endDate: '2025-11-09',
    contact: '王经理',
    phone: '13112345678',
    email: 'wang@iflytek.com',
    address: '合肥市高新区望江西路666号',
    status: 'active',
  },
  {
    id: 18,
    name: '浙江大学',
    type: 'academic',
    industry: '教育',
    description: '学术交流与科研合作，联合培养学生，共同申报项目。',
    startDate: '2022-05-25',
    endDate: '2027-05-24',
    contact: '赵教授',
    phone: '0571-12345678',
    email: 'zhao@zju.edu.cn',
    address: '杭州市西湖区余杭塘路866号',
    status: 'active',
  },
  {
    id: 19,
    name: '联想集团',
    type: 'enterprise',
    industry: '电子产品',
    description: '计算机硬件技术合作，共建实验室，提供实习和就业机会。',
    startDate: '2022-12-15',
    endDate: '2025-12-14',
    contact: '钱总监',
    phone: '13012345678',
    email: 'qian@lenovo.com',
    address: '北京市海淀区上地西路6号',
    status: 'active',
  },
  {
    id: 20,
    name: '南京大学',
    type: 'academic',
    industry: '教育',
    description: '学术交流与科研合作，联合培养研究生，共同举办学术会议。',
    startDate: '2022-06-30',
    endDate: '2027-06-29',
    contact: '孙教授',
    phone: '025-12345678',
    email: 'sun@nju.edu.cn',
    address: '南京市鼓楼区汉口路22号',
    status: 'active',
  },
];