import { Organization } from '@/types';

// 模拟数据 - 20条组织记录
export const mockOrganizationData: Organization[] = [
  {
    id: 1,
    name: '北京校友会',
    type: 'branch',
    description: '服务北京地区校友，组织各类活动和交流。',
    foundingDate: '2010-05-15',
    leader: '张明',
    memberCount: 520,
    contactEmail: 'beijing@alumni.edu.cn',
    contactPhone: '010-12345678',
    contact: '李秘书',
    location: '北京市海淀区',
    status: 'active',
  },
  {
    id: 2,
    name: '创业俱乐部',
    type: 'club',
    description: '为创业校友提供交流平台和资源对接。',
    foundingDate: '2015-03-20',
    leader: '王强',
    memberCount: 180,
    contactEmail: 'startup@alumni.edu.cn',
    contactPhone: '13812345678',
    contact: '赵创',
    location: '线上',
    status: 'active',
  },
  {
    id: 3,
    name: '上海校友会',
    type: 'branch',
    description: '连接上海地区校友，促进校友间交流与合作。',
    foundingDate: '2011-09-10',
    leader: '陈晓',
    memberCount: 480,
    contactEmail: 'shanghai@alumni.edu.cn',
    contactPhone: '021-87654321',
    contact: '钱秘书',
    location: '上海市徐汇区',
    status: 'active',
  },
  {
    id: 4,
    name: '金融投资协会',
    type: 'association',
    description: '专注于金融领域的校友交流与资源共享。',
    foundingDate: '2016-11-05',
    leader: '孙金',
    memberCount: 150,
    contactEmail: 'finance@alumni.edu.cn',
    contactPhone: '13987654321',
    contact: '周投',
    location: '线上+线下',
    status: 'active',
  },
  {
    id: 5,
    name: '广州校友会',
    type: 'branch',
    description: '服务广州及珠三角地区校友。',
    foundingDate: '2012-04-18',
    leader: '林广',
    memberCount: 320,
    contactEmail: 'guangzhou@alumni.edu.cn',
    contactPhone: '020-12345678',
    contact: '黄秘书',
    location: '广州市天河区',
    status: 'active',
  },
  {
    id: 6,
    name: 'IT技术联盟',
    type: 'alliance',
    description: '连接IT行业校友，分享技术趋势和就业信息。',
    foundingDate: '2017-07-22',
    leader: '吴程',
    memberCount: 230,
    contactEmail: 'it@alumni.edu.cn',
    contactPhone: '13512345678',
    contact: '郑码',
    location: '线上',
    status: 'active',
  },
  {
    id: 7,
    name: '深圳校友会',
    type: 'branch',
    description: '服务深圳地区校友，促进创新创业。',
    foundingDate: '2013-10-08',
    leader: '刘深',
    memberCount: 380,
    contactEmail: 'shenzhen@alumni.edu.cn',
    contactPhone: '0755-12345678',
    contact: '谢秘书',
    location: '深圳市南山区',
    status: 'active',
  },
  {
    id: 8,
    name: '艺术文化协会',
    type: 'association',
    description: '促进校友间艺术交流与文化活动。',
    foundingDate: '2018-03-15',
    leader: '张艺',
    memberCount: 120,
    contactEmail: 'art@alumni.edu.cn',
    contactPhone: '13612345678',
    contact: '李画',
    location: '线上+线下',
    status: 'active',
  },
  {
    id: 9,
    name: '成都校友会',
    type: 'branch',
    description: '连接成都及西南地区校友。',
    foundingDate: '2014-05-20',
    leader: '王蜀',
    memberCount: 260,
    contactEmail: 'chengdu@alumni.edu.cn',
    contactPhone: '028-12345678',
    contact: '熊秘书',
    location: '成都市武侯区',
    status: 'active',
  },
  {
    id: 10,
    name: '医疗健康联盟',
    type: 'alliance',
    description: '连接医疗健康领域校友，分享行业资源。',
    foundingDate: '2019-09-10',
    leader: '李医',
    memberCount: 180,
    contactEmail: 'health@alumni.edu.cn',
    contactPhone: '13712345678',
    contact: '张护',
    location: '线上',
    status: 'active',
  },
  {
    id: 11,
    name: '武汉校友会',
    type: 'branch',
    description: '服务武汉及华中地区校友。',
    foundingDate: '2015-03-12',
    leader: '陈楚',
    memberCount: 290,
    contactEmail: 'wuhan@alumni.edu.cn',
    contactPhone: '027-12345678',
    contact: '刘秘书',
    location: '武汉市洪山区',
    status: 'active',
  },
  {
    id: 12,
    name: '教育发展基金会',
    type: 'foundation',
    description: '支持母校教育事业发展的非营利组织。',
    foundingDate: '2016-06-18',
    leader: '王教',
    memberCount: 85,
    contactEmail: 'education@alumni.edu.cn',
    contactPhone: '13812345679',
    contact: '赵基',
    location: '校内',
    status: 'active',
  },
  {
    id: 13,
    name: '西安校友会',
    type: 'branch',
    description: '连接西安及西北地区校友。',
    foundingDate: '2016-10-15',
    leader: '李西',
    memberCount: 210,
    contactEmail: 'xian@alumni.edu.cn',
    contactPhone: '029-12345678',
    contact: '张秘书',
    location: '西安市雁塔区',
    status: 'active',
  },
  {
    id: 14,
    name: '体育运动协会',
    type: 'association',
    description: '组织校友体育活动，促进健康生活。',
    foundingDate: '2017-04-25',
    leader: '刘体',
    memberCount: 160,
    contactEmail: 'sports@alumni.edu.cn',
    contactPhone: '13912345678',
    contact: '孙跑',
    location: '线上+线下',
    status: 'active',
  },
  {
    id: 15,
    name: '杭州校友会',
    type: 'branch',
    description: '服务杭州地区校友，促进互联网行业交流。',
    foundingDate: '2017-08-08',
    leader: '张杭',
    memberCount: 310,
    contactEmail: 'hangzhou@alumni.edu.cn',
    contactPhone: '0571-12345678',
    contact: '王秘书',
    location: '杭州市西湖区',
    status: 'active',
  },
  {
    id: 16,
    name: '环保公益联盟',
    type: 'alliance',
    description: '关注环保议题，组织校友参与公益活动。',
    foundingDate: '2018-06-05',
    leader: '陈绿',
    memberCount: 95,
    contactEmail: 'green@alumni.edu.cn',
    contactPhone: '13612345679',
    contact: '林水',
    location: '线上',
    status: 'active',
  },
  {
    id: 17,
    name: '南京校友会',
    type: 'branch',
    description: '连接南京及江苏地区校友。',
    foundingDate: '2018-11-20',
    leader: '王宁',
    memberCount: 240,
    contactEmail: 'nanjing@alumni.edu.cn',
    contactPhone: '025-12345678',
    contact: '李秘书',
    location: '南京市鼓楼区',
    status: 'active',
  },
  {
    id: 18,
    name: '法律服务团',
    type: 'service',
    description: '由法律专业校友组成，提供法律咨询服务。',
    foundingDate: '2019-03-15',
    leader: '张法',
    memberCount: 75,
    contactEmail: 'legal@alumni.edu.cn',
    contactPhone: '13712345679',
    contact: '王律',
    location: '线上+线下',
    status: 'active',
  },
  {
    id: 19,
    name: '重庆校友会',
    type: 'branch',
    description: '服务重庆地区校友。',
    foundingDate: '2019-07-01',
    leader: '李渝',
    memberCount: 190,
    contactEmail: 'chongqing@alumni.edu.cn',
    contactPhone: '023-12345678',
    contact: '陈秘书',
    location: '重庆市渝中区',
    status: 'active',
  },
  {
    id: 20,
    name: '青年创新论坛',
    type: 'forum',
    description: '为年轻校友提供创新交流平台。',
    foundingDate: '2020-01-10',
    leader: '王新',
    memberCount: 130,
    contactEmail: 'innovation@alumni.edu.cn',
    contactPhone: '13812345670',
    contact: '张创',
    location: '线上',
    status: 'active',
  },
];