import { Donation } from '@/types';

// 模拟数据 - 20条捐赠记录
export const mockDonationData: Donation[] = [
  {
    id: 1,
    donorName: '张三',
    amount: 10000,
    donationDate: '2024-01-15',
    purpose: '奖学金',
    projectName: '优秀学生奖学金',
    status: 'completed',
    remarks: '希望资助品学兼优的学生',
    thanksLetterSent: true,
  },
  {
    id: 2,
    donorName: '李四企业',
    amount: 500000,
    donationDate: '2024-02-20',
    purpose: '科研基金',
    projectName: '人工智能研究中心',
    status: 'completed',
    remarks: '支持学校人工智能领域研究',
    thanksLetterSent: false,
  },
  {
    id: 3,
    donorName: '王五',
    amount: 5000,
    donationDate: '2024-03-05',
    purpose: '图书馆建设',
    projectName: '图书馆藏书扩充计划',
    status: 'completed',
    remarks: '捐赠用于购买专业书籍',
    thanksLetterSent: true,
  },
  {
    id: 4,
    donorName: '赵六基金会',
    amount: 1000000,
    donationDate: '2024-01-30',
    purpose: '校园建设',
    projectName: '新教学楼建设项目',
    status: 'completed',
    remarks: '支持学校基础设施建设',
    thanksLetterSent: true,
  },
  {
    id: 5,
    donorName: '钱七',
    amount: 8000,
    donationDate: '2024-02-15',
    purpose: '学生活动',
    projectName: '校园文化节',
    status: 'completed',
    remarks: '支持校园文化活动开展',
    thanksLetterSent: false,
  },
  {
    id: 6,
    donorName: '孙八科技有限公司',
    amount: 300000,
    donationDate: '2024-03-10',
    purpose: '创新创业',
    projectName: '学生创业孵化基金',
    status: 'completed',
    remarks: '支持学生创业项目',
    thanksLetterSent: true,
  },
  {
    id: 7,
    donorName: '周九',
    amount: 15000,
    donationDate: '2024-01-20',
    purpose: '助学金',
    projectName: '困难学生资助计划',
    status: 'completed',
    remarks: '帮助家庭困难学生完成学业',
    thanksLetterSent: true,
  },
  {
    id: 8,
    donorName: '吴十教育基金会',
    amount: 200000,
    donationDate: '2024-02-28',
    purpose: '教师发展',
    projectName: '教师海外研修项目',
    status: 'completed',
    remarks: '资助教师赴海外进修学习',
    thanksLetterSent: false,
  },
  {
    id: 9,
    donorName: '郑十一',
    amount: 20000,
    donationDate: '2024-03-15',
    purpose: '体育发展',
    projectName: '校运动队装备更新',
    status: 'completed',
    remarks: '为校运动队购置新装备',
    thanksLetterSent: true,
  },
  {
    id: 10,
    donorName: '王十二集团',
    amount: 800000,
    donationDate: '2024-01-25',
    purpose: '实验室建设',
    projectName: '先进材料实验室',
    status: 'completed',
    remarks: '支持学校科研设施建设',
    thanksLetterSent: true,
  },
  {
    id: 11,
    donorName: '李十三',
    amount: 30000,
    donationDate: '2024-02-10',
    purpose: '校友活动',
    projectName: '校友返校日',
    status: 'completed',
    remarks: '赞助校友返校活动经费',
    thanksLetterSent: false,
  },
  {
    id: 12,
    donorName: '赵十四医疗集团',
    amount: 400000,
    donationDate: '2024-03-20',
    purpose: '医学研究',
    projectName: '医学院研究基金',
    status: 'completed',
    remarks: '支持医学领域前沿研究',
    thanksLetterSent: true,
  },
  {
    id: 13,
    donorName: '张十五',
    amount: 12000,
    donationDate: '2024-01-18',
    purpose: '艺术发展',
    projectName: '艺术学院展演基金',
    status: 'completed',
    remarks: '支持艺术类学生展演活动',
    thanksLetterSent: true,
  },
  {
    id: 14,
    donorName: '刘十六科技公司',
    amount: 250000,
    donationDate: '2024-02-22',
    purpose: '信息化建设',
    projectName: '智慧校园项目',
    status: 'completed',
    remarks: '推动学校信息化建设',
    thanksLetterSent: false,
  },
  {
    id: 15,
    donorName: '陈十七',
    amount: 18000,
    donationDate: '2024-03-08',
    purpose: '国际交流',
    projectName: '学生海外交换项目',
    status: 'completed',
    remarks: '资助学生参与国际交流项目',
    thanksLetterSent: true,
  },
  {
    id: 16,
    donorName: '杨十八基金会',
    amount: 350000,
    donationDate: '2024-01-28',
    purpose: '学科建设',
    projectName: '一流学科建设基金',
    status: 'completed',
    remarks: '支持学校重点学科发展',
    thanksLetterSent: true,
  },
  {
    id: 17,
    donorName: '吴十九',
    amount: 25000,
    donationDate: '2024-02-18',
    purpose: '社会实践',
    projectName: '学生社会实践项目',
    status: 'completed',
    remarks: '支持学生开展社会实践活动',
    thanksLetterSent: false,
  },
  {
    id: 18,
    donorName: '郭二十教育科技公司',
    amount: 180000,
    donationDate: '2024-03-12',
    purpose: '在线教育',
    projectName: '在线课程建设项目',
    status: 'completed',
    remarks: '支持学校在线教育平台建设',
    thanksLetterSent: true,
  },
  {
    id: 19,
    donorName: '林二十一',
    amount: 15000,
    donationDate: '2024-01-22',
    purpose: '心理健康',
    projectName: '心理健康中心建设',
    status: 'completed',
    remarks: '关注学生心理健康发展',
    thanksLetterSent: true,
  },
  {
    id: 20,
    donorName: '黄二十二投资公司',
    amount: 500000,
    donationDate: '2024-03-01',
    purpose: '创新基金',
    projectName: '科技创新基金',
    status: 'pending',
    remarks: '支持学校科技创新项目',
    thanksLetterSent: false,
  },
];