import { Alumni } from '@/types';

// 模拟数据 - 20条校友记录
export const mockAlumniData: Alumni[] = [
  {
    id: 1,
    studentId: '20160101',
    name: '张三',
    gender: '男',
    school: '计算机学院',
    major: '软件工程',
    graduationYear: '2020',
    degree: '本科',
    currentCompany: '腾讯',
    jobPosition: '前端开发工程师',
  },
  {
    id: 2,
    studentId: '20160102',
    name: '李四',
    gender: '女',
    school: '电子信息学院',
    major: '电子工程',
    graduationYear: '2020',
    degree: '硕士',
    currentCompany: '阿里巴巴',
    jobPosition: '算法工程师',
  },
  {
    id: 3,
    studentId: '20150103',
    name: '王五',
    gender: '男',
    school: '管理学院',
    major: '工商管理',
    graduationYear: '2019',
    degree: '本科',
    currentCompany: '字节跳动',
    jobPosition: '产品经理',
  },
  {
    id: 4,
    studentId: '20170104',
    name: '赵六',
    gender: '女',
    school: '外国语学院',
    major: '英语',
    graduationYear: '2021',
    degree: '本科',
    currentCompany: '华为',
    jobPosition: '国际业务专员',
  },
  {
    id: 5,
    studentId: '20140105',
    name: '钱七',
    gender: '男',
    school: '人工智能学院',
    major: '人工智能',
    graduationYear: '2018',
    degree: '博士',
    currentCompany: '百度',
    jobPosition: '研究员',
  },
  {
    id: 6,
    studentId: '20150106',
    name: '孙八',
    gender: '男',
    school: '材料科学学院',
    major: '材料工程',
    graduationYear: '2019',
    degree: '硕士',
    currentCompany: '中国石化',
    jobPosition: '材料研发工程师',
  },
  {
    id: 7,
    studentId: '20160107',
    name: '周九',
    gender: '女',
    school: '经济学院',
    major: '金融学',
    graduationYear: '2020',
    degree: '本科',
    currentCompany: '中国银行',
    jobPosition: '金融分析师',
  },
  {
    id: 8,
    studentId: '20170108',
    name: '吴十',
    gender: '男',
    school: '法学院',
    major: '法学',
    graduationYear: '2021',
    degree: '本科',
    currentCompany: '金杜律师事务所',
    jobPosition: '律师助理',
  },
  {
    id: 9,
    studentId: '20150109',
    name: '郑十一',
    gender: '女',
    school: '医学院',
    major: '临床医学',
    graduationYear: '2019',
    degree: '博士',
    currentCompany: '北京协和医院',
    jobPosition: '医生',
  },
  {
    id: 10,
    studentId: '20160110',
    name: '王十二',
    gender: '男',
    school: '建筑学院',
    major: '建筑设计',
    graduationYear: '2020',
    degree: '硕士',
    currentCompany: '中国建筑设计院',
    jobPosition: '建筑师',
  },
  {
    id: 11,
    studentId: '20140111',
    name: '李十三',
    gender: '女',
    school: '艺术学院',
    major: '数字媒体艺术',
    graduationYear: '2018',
    degree: '本科',
    currentCompany: '网易游戏',
    jobPosition: 'UI设计师',
  },
  {
    id: 12,
    studentId: '20180112',
    name: '刘十四',
    gender: '男',
    school: '体育学院',
    major: '体育教育',
    graduationYear: '2022',
    degree: '本科',
    currentCompany: '北京市第一中学',
    jobPosition: '体育教师',
  },
  {
    id: 13,
    studentId: '20170113',
    name: '陈十五',
    gender: '女',
    school: '新闻传播学院',
    major: '新闻学',
    graduationYear: '2021',
    degree: '本科',
    currentCompany: 'CCTV',
    jobPosition: '记者',
  },
  {
    id: 14,
    studentId: '20160114',
    name: '杨十六',
    gender: '男',
    school: '物理学院',
    major: '理论物理',
    graduationYear: '2020',
    degree: '博士',
    currentCompany: '中国科学院',
    jobPosition: '研究员',
  },
  {
    id: 15,
    studentId: '20150115',
    name: '赵十七',
    gender: '女',
    school: '化学学院',
    major: '应用化学',
    graduationYear: '2019',
    degree: '硕士',
    currentCompany: '上海化工研究所',
    jobPosition: '化学工程师',
  },
  {
    id: 16,
    studentId: '20140116',
    name: '钱十八',
    gender: '男',
    school: '数学学院',
    major: '统计学',
    graduationYear: '2018',
    degree: '本科',
    currentCompany: '德勤',
    jobPosition: '数据分析师',
  },
  {
    id: 17,
    studentId: '20180117',
    name: '孙十九',
    gender: '女',
    school: '外语学院',
    major: '日语',
    graduationYear: '2022',
    degree: '本科',
    currentCompany: '丰田汽车',
    jobPosition: '对外联络专员',
  },
  {
    id: 18,
    studentId: '20170118',
    name: '周二十',
    gender: '男',
    school: '环境学院',
    major: '环境工程',
    graduationYear: '2021',
    degree: '硕士',
    currentCompany: '生态环境部',
    jobPosition: '环境评估工程师',
  },
  {
    id: 19,
    studentId: '20160119',
    name: '吴二一',
    gender: '女',
    school: '心理学院',
    major: '应用心理学',
    graduationYear: '2020',
    degree: '本科',
    currentCompany: '京东',
    jobPosition: '用户体验研究员',
  },
  {
    id: 20,
    studentId: '20150120',
    name: '郑二二',
    gender: '男',
    school: '机械工程学院',
    major: '机械自动化',
    graduationYear: '2019',
    degree: '硕士',
    currentCompany: '比亚迪',
    jobPosition: '自动化工程师',
  },
];
